spring:
  application:
    name: crm-ticket
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    virtual-host: /

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://10.177.2.29:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info
