server:
    port: 9002

spring:
    application:
        name: CMS-USER

#eureka:
#  client:
#    registerWithEureka: true
#    serviceUrl:
#      defaultZone: ${EUREKA_SERVER:http://10.177.2.21:8761/eureka}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost


management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info
